# Generated by Django 3.1.3 on 2021-03-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activedetail',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='activedetail',
            name='start_time',
        ),
        migrations.AddField(
            model_name='activedetail',
            name='endTime',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='activedetail',
            name='startTime',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='active',
            name='end_time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='active',
            name='start_time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='activedetail',
            name='active_type',
            field=models.IntegerField(),
        ),
    ]
