# Generated by Django 3.1.3 on 2021-03-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_email', models.CharField(max_length=200)),
                ('nickname', models.CharField(max_length=50)),
                ('profile_img', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('leader_pk', models.IntegerField()),
                ('max_user', models.IntegerField()),
                ('group_img', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('member', models.ManyToManyField(related_name='group', to='users.User')),
            ],
        ),
    ]
