# Generated by Django 3.1.3 on 2021-03-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210315_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_img',
            field=models.CharField(max_length=1000),
        ),
    ]
